ALTER TABLE tracks ADD COLUMN IF NOT EXISTS genre TEXT NOT NULL DEFAULT '';
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS lyrics_srt TEXT NOT NULL DEFAULT '';

ALTER TABLE albums ADD COLUMN IF NOT EXISTS genre TEXT NOT NULL DEFAULT '';
